## ============================================================================
## ================================ PRODUCTION ================================
## ============================================================================


server.port=${PORT}
spring.application.name=api-gateway

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=${AUTH_SERVICE_URL:https://auth-service:10000}
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**,/api/test/**
#spring.cloud.gateway.routes[0].filters[0]=JwtAuthFilter

spring.cloud.gateway.routes[1].id=api-general
spring.cloud.gateway.routes[1].uri=${GRAL_SERVICES_URL:https://checklist-api:10000}
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/**

spring.cloud.gateway.routes[2].id=job-service
spring.cloud.gateway.routes[2].uri=${JOB_SERVICE_URL:https://job-service:10000}
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v2/job-management/**, /uploads/signatures/**

spring.cloud.gateway.routes[3].id=payroll-service
spring.cloud.gateway.routes[3].uri=${PAYROLL_SERVICE_URL:https://payroll-service:10000}
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v2/payroll/**

spring.cloud.gateway.routes[4].id=work-service
spring.cloud.gateway.routes[4].uri=${WORK_SPACE_SERVICE_URL:https://work-service:10000}
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v2/work-space/**

spring.cloud.gateway.routes[5].id=delay-log
spring.cloud.gateway.routes[5].uri=${DELAY_TRACKER_SERVICE_URL:https://delay-tracker-service:10000}
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/v2/delay-log/**

spring.cloud.gateway.routes[6].id=delay-log-signatures-public
spring.cloud.gateway.routes[6].uri=${DELAY_TRACKER_SERVICE_URL:https://delay-tracker-service:10000}
spring.cloud.gateway.routes[6].predicates[0]=Path=/uploads/delay-log/signatures/**

spring.cloud.gateway.routes[7].id=maintenance-service
spring.cloud.gateway.routes[7].uri=${MAINTENANCE_SERVICE_URL:https://maintenance-service:10000}
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/v2/maintenance/**

application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.expiration=900000

spring.codec.max-in-memory-size=50MB

spring.cloud.gateway.httpclient.connect-timeout=10000
spring.cloud.gateway.httpclient.response-timeout=60s
spring.cloud.gateway.httpclient.pool.type=elastic
spring.cloud.gateway.httpclient.pool.max-idle-time=15s
spring.cloud.gateway.httpclient.pool.max-life-time=60s

spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.com.gateway.filter.JwtAuthFilter=INFO
logging.level.org.springframework.security=DEBUG

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1

spring.datasource.hikari.max-lifetime=25000
spring.datasource.hikari.idle-timeout=20000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.keepalive-time=15000

spring.datasource.hikari.initialization-fail-timeout=0